apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: golang-microservice-example
  annotations:
    github.com/project-slug: rail/golang-microservice-example
spec:
  type: other
  lifecycle: unknown
  owner: team-a
